# Generated by Django 5.0.3 on 2024-04-19 02:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='location',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='barcode',
            new_name='domain_user',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='name',
            new_name='pc_name',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='supplier',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='costs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='date_delivered',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='device_type',
            field=models.CharField(default='Laptop', max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='has_cd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='has_dock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='has_keyboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='has_lcd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='has_lcd2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='has_stand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_computer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='new_computer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
