# Generated by Django 5.0.3 on 2024-04-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_location_inventoryitem_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
