# Generated by Django 5.0.3 on 2024-03-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="barcode",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
