# Generated by Django 5.0.3 on 2024-03-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0004_supplier_inventoryitem_location_inventoryitem_notes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="website",
            field=models.CharField(default="----", max_length=200),
            preserve_default=False,
        ),
    ]
