# Generated by Django 5.0.3 on 2024-03-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_supplier_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="website",
            field=models.TextField(blank=True),
        ),
    ]
