# Generated by Django 5.0.3 on 2024-03-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_supplier_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='model_number',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
