# Generated by Django 5.0.3 on 2024-04-22 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_department_alter_inventoryitem_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
    ]
