# Generated by Django 5.0.3 on 2024-04-27 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_person_alter_checkout_checked_out_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checked_out_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_to', to='inventory.person'),
        ),
    ]
