# Generated by Django 5.0.3 on 2024-05-05 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_checkout_checked_out_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='domain_user',
            field=models.CharField(blank=True, max_length=101),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checked_out_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
