# Generated by Django 5.0.3 on 2024-04-04 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_alter_inventoryitem_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkout",
            old_name="checked_out_to",
            new_name="user",
        ),
    ]
