# Generated by Django 5.0.3 on 2024-05-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_person_domain_user_alter_checkout_checked_out_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='domain_user',
        ),
    ]
