# Generated by Django 5.0.3 on 2024-05-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_inventoryitem_department_person_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'person', 'verbose_name_plural': 'persons'},
        ),
    ]
